### ISSUE TITLE
Which clip features do you use for MAD dataset?

### ISSUE THREAD

**Issue by fake-warrior8** [houzhijian/CONE#5]
Hi, I'd like to know which CLIP feature you are using for MAD dataset. Is it CLIP_B32 or CLIP_L14? By the way, I unzip your Ego4D tar.gz and found two files, egovlp_video_feature_1.87fps.tar.gz and egovlp_video_feature_1.875fps.tar.gz, which one did you use, and there doesn't seem to be much difference between the two.

**Comment by houzhijian** [comment]
Hi, the CLIP features are extracted from the MAD authors. I suggest you ask the original authors for a more accurate reply. 

The difference between egovlp_video_feature_1.87fps.tar.gz and egovlp_video_feature_1.875fps.tar.gz is the frame sampling rate. One is 1.87fps, and another is 1.875fps. **Those two should have little difference.** I recommend you use 1.875fps because 1.875fps means precisely extracting one feature per 16 frames (feature duration: 16/30 = 0.5333).  I release the feature version of 1.87fps following the standard EgoVLP code setting (https://github.com/showlab/EgoVLP/blob/f3e8895c7a1a691bc7fb0c07618c3be0015887eb/data_loader/Ego4D_NLQ_dataset.py#L78).
